### ISSUE TITLE
data capture stops at midnight

### ISSUE THREAD

**Issue by WorksofFaith** [MORE-Platform/more-app-multiplatform#175]
Data capture for passive sensing sensors (e.g. Acc, GPS) stops at midnight. For the next day observation app needs to be opened again. Next day observation don't start automatically. 

 (Devender)

**Comment by andresgruber** [comment]
1. Data capture does not stop at midnight if there is observation scheduled from e.g. 22:00 - 02:00. Note: It might be the case, that the observation stops for other reasons such as low battery of the phone or the external device or other actions generated by the 
2. Data capture will stop, if the observation is scheduled as recurring whole day observations.
