### ISSUE TITLE
Preventing Observation Launch from Notification Page After Observation Time Has Passed or Participants Have Responded.

### ISSUE THREAD

**Issue by alireza-dhp** [MORE-Platform/more-app-multiplatform#221]
There is an issue with the notification tab functionality related to running observations.
The problem arises when participants receive notifications for interventions involving observations (e.g., Limesurvey or a simple questionnaire). Participants can initiate the corresponding observation at any time, irrespective of the valid time range specified for the observation.

Additionally, it has been observed that even if an observation's time range has passed or participants have already responded to it via the dashboard page, the observation for the next scheduled time is automatically filled out instead!

To provide a clearer understanding of this issue, I have attached a video demonstrating the bug. 
The expected behavior is to restrict observation execution based on the valid time range of an observation and prevent participants from responding if the observation has already been answered.

Please review the attached video for more details on this issue.
https://www.loom.com/share/149d2e2894bb46668157e600424ae70a?sid=6222216d-73fd-4d2a-9a17-b7cd4a48c78e

**Comment by alireza-dhp** [comment]
Hi @janoliver20, @andresgruber 
Tapping on notifications, which includes an action (LimeSurvey or Simple Questionnaire), does not function as intended in version 3.0.8 on **Android** devices. It works on iOS! 
It has been tested on Android verion 13 and 12.
This verion (3.0.8) has been created after pull request #222.
apk file:
https://drive.google.com/file/d/1RKYO0izHB2uT0oU-kjbsHHqXRzq4BlLS/view?usp=sharing

**Comment by alireza-dhp** [comment]
> Hi @janoliver20, @andresgruber Tapping on notifications, which includes an action (LimeSurvey or Simple Questionnaire), does not function as intended in version 3.0.8 on **Android** devices. It works on iOS! It has been tested on Android verion 13 and 12. This verion (3.0.8) has been created after pull request #222. apk file: https://drive.google.com/file/d/1RKYO0izHB2uT0oU-kjbsHHqXRzq4BlLS/view?usp=sharing

Please review the attached video for more details on this issue:
https://www.loom.com/share/b1007767d6c04d0082d137d4d227baa7?sid=801afe6b-0945-488b-a035-c8a58af23ada

**Comment by andresgruber** [comment]
Dear @alireza-dhp In parallel to https://github.com/MORE-Platform/more-app-multiplatform/pull/229/ we have also tried to reproduce the issue you report here: action notifications on Android, but without success. After merging the pull request and building the App versions 3.0.9 for Android, pls test again, whether this behavior stays.

**Comment by alireza-dhp** [comment]
Dear @andresgruber,

We still have this issue on the new (3.0.9) Android version!
APK file:
https://drive.google.com/file/d/1hHgHwlQCWTKpClmk4kgMxv4vbPOq5kqY/view?usp=sharing

**Comment by alireza-dhp** [comment]
> Dear @andresgruber,
> 
> We still have this issue on the new (3.0.9) Android version! APK file: https://drive.google.com/file/d/1hHgHwlQCWTKpClmk4kgMxv4vbPOq5kqY/view?usp=sharing

This issue is solved by PR #230
