### ISSUE TITLE
Opening multiple lime surveys issue

### ISSUE THREAD

**Issue by alireza-dhp** [MORE-Platform/more-app-multiplatform#223]
When multiple LimeSurveys are active on the dashboard or notification page, users encounter an issue where tapping on the first Lime Survey functions correctly. However, when attempting to tap on the second survey, users are redirected to the previous survey instead of the intended one. This behavior is observed on iPhones.
Please review the attached video for more details on this issue:
https://www.loom.com/share/975b2d37fc7a413ab6b6dd668eccdce5?sid=e4ae6ece-aa62-41f7-812d-c37913198947

**Comment by andresgruber** [comment]
To investigate further into the issue, please provide us with further information:

1. Version of the MORE backend
2. Version of the MORE iOS app (from the screen video I would guess its v3.0.8)
3. Configuration of the study used

and pls confirm/reject/comment my perceptions of the case (from your video):

- the behavior is observed in case  you don't complete the first questionnaire - does it happen if you finish the first questionnaire?
- the behavior is observed when clicking in this exact order - does ist also happen if one would open the second questionnaires first?
- the behavior is observed with lime survey - does it also happen with other observations, such as two simple questions?

**Comment by alireza-dhp** [comment]
1- We're using the MORE platform's staging version, based on the redlink-staging branch.
https://github.com/MORE-Platform/more-studymanager-backend/tree/redlink-staging
The Docker files are tagged with "staging," and the backend Docker image is available at 
ghcr.io/more-platform/more-study-manager-backend:staging.

2- The MORE iOS app version on the staging development is 3.0.8. @andresgruber and @janoliver20 should have access to this version.

3- I've set up a new study on the dev instance, and you can access it using the "Office@redlink.at" user account. 
The study is available at https://studymanager.dev.more-health.at/studies/19.
Here is the study config as well:
[study_config_19.json](https://github.com/MORE-Platform/more-app-multiplatform/files/14416774/study_config_19.json)


- Even if the first LimeSurvey is completed, tapping the second one loads the previous LimeSurvey.
- The behavior occurs regardless of the tapping order. The first tapped LimeSurvey is loaded for the second tapped one.
- The issue doesn't occur with a simple questionnaire.

**Comment by andresgruber** [comment]
@alireza-dhp could you please tell me, from which branch you have built the app version 3.0.8 ?

**Comment by alireza-dhp** [comment]
The 3.0.8 version has been build by redlink-staging branch:
https://github.com/MORE-Platform/more-app-multiplatform/tree/redlink-staging

**Comment by andresgruber** [comment]
Thank you @alireza-dhp We have built form the same branch and get the version 3.0.7, b/c this is the version mentioned in [Info.plist](https://github.com/MORE-Platform/more-app-multiplatform/blob/redlink-staging/iosApp/iosApp/Info.plist) so there is still a little mysterious difference to sort out, but nonetheless, we can reproduce the bug and are working on fixing it.

**Comment by alireza-dhp** [comment]
This issue is solved by PR #229
