### ISSUE TITLE
Displaying the daily observations twice!

### ISSUE THREAD

**Issue by alireza-dhp** [MORE-Platform/more-app-multiplatform#226]
The dashboard displays the daily observations twice!
We duplicate a study, could this be the reason?
![download](https://github.com/MORE-Platform/more-app-multiplatform/assets/107924035/bb988f58-706e-4ebe-a054-509c5395bc53)

**Comment by andresgruber** [comment]
Thank you @alireza-dhp for the video, we will test with the tokens you provided. In addition, to dive deeper please send us your study config so that we can also test with our test infrastructure to ensure, that it is not related to some setup.

**Comment by alireza-dhp** [comment]
Dear @andresgruber,
The study config file is enclosed!
[study_config_19.json](https://github.com/MORE-Platform/more-app-multiplatform/files/14612121/study_config_19.json)

You have access to this study via office redlink account:
https://studymanager.dev.more-health.at/studies/19

**Comment by alireza-dhp** [comment]
Apparently, displaying observations twice disappears when you close and reopen the iOS app.
The behaviour is observed for the participants who are already logged in to the app.
