### ISSUE TITLE
Support for Android 14

### ISSUE THREAD

**Issue by ja-fra** [MORE-Platform/more-app-multiplatform#245]
Android 14 is out for quite some time but requires some adaptions.

**Comment by andresgruber** [comment]
@janoliver20 Could you please describe briefly, what the status w.r.t. Android 14 is. What happens, if a participant joins a study with Android 14+  and what needs to be changed to support the new versions fully?

**Comment by janoliver20** [comment]
Android 14 introduced a new security feature, which requires developers to add a list of required Device Hardware to Foreground Services, else if a Hardware SDK is implemented, but not added, the app will be killed by the system.
