### ISSUE TITLE
Show an App-Indicator when having unread notifications in the Notification Center

### ISSUE THREAD

**Issue by ja-fra** [MORE-Platform/more-app-multiplatform#251]
When the participant has unread messages in the notification-center, show an app-indicator on the app-icon (if possible, including the number of unread messages)

**Comment by alireza-dhp** [comment]
This ticket has been created regarding the following feedback from a participant of a running study (ACTIVE WAITING study):

> Feedback from another participant concerning push notifications: push notifications “disappear” as soon as the mobile phone is unlocked, they are not visible anymore, therefore not reminding her to do the survey. The participant suggested whether it would be possible to have a reminder (eg every 15 Min, which could be set individually), or if the open task could be displayed in the icon of the MORE App (similar to unread messages in Signal/WhatsApp/SMS).

**Comment by alireza-dhp** [comment]
Here is feedback from a participant:

> Another participant informed me, that she randomly does not receive push-notifications. Unfortunately, I couldn't find out whether it was an issue of not receiving the push-notification, or whether the push notification was sent but disappeared when unlocking/using the phone. 
She uses a Huawei P10 lite (Version 12.0.0)

Apart from checking the backend logs for sending push notifications, is there a way on the app side to ensure that the participants receive the push notifications?

**Comment by janoliver20** [comment]
The badge is now implemented in both Android and iOS and showing the amount of unread push notifications. Android shows a either a bubble or a badge with the notification count, depending on the launcher. Unfortunately a few Samsung devices, including our test devices, experience a certain [bug](https://eu.community.samsung.com/t5/galaxy-s23-series/notifications-disaster-app-badge-count-quot-feature-quot-bug/td-p/7654958) that increment by one or two too much, if a notification is received while the app is open. If the app is opened and closed again, it will show the correct amount of notifications again in the badge.
