### ISSUE TITLE
Push notifications are not received randomly.

### ISSUE THREAD

**Issue by alireza-dhp** [MORE-Platform/more-app-multiplatform#256]
> Here is feedback from a participant:
> 
> 
> 
> Another participant informed me, that she randomly does not receive push-notifications. Unfortunately, I couldn't find out whether it was an issue of not receiving the push-notification, or whether the push notification was sent but disappeared when unlocking/using the phone. 
> 
> She uses a Huawei P10 lite (Version 12.0.0)
> 
> 
> 
> Apart from checking the backend logs for sending push notifications, is there a way on the app side to ensure that the participants receive the push notifications? 

 _Originally posted by @alireza-dhp in [#251](https://github.com/MORE-Platform/more-app-multiplatform/issues/251#issuecomment-2122007385)_

The study config file is enclosed.
[study_config_8.json](https://github.com/MORE-Platform/more-app-multiplatform/files/15483470/study_config_8.json)

**Comment by alireza-dhp** [comment]
Dear @andresgruber 

To simulate the bug where notifications in the notification center (NC) are missed on both platforms, follow these steps:
 
- Sign in to a study that has an intervention.
- Close the app.
- Pause the study. (You receive a notification about pausing the study, and all former messages will be deleted from NC. in this stage.)
- Resume the study. (Another push notification will arrive, indicating that the study has been resumed.)
- Do not open the app before receiving at least one intervention as a push notification message.
- When you receive the intervention, open the app, you will observe that there are no messages in the NC!

It seems that all push notification messages are missed in the NC after a study is paused until the app is opened for the first time.

**Comment by andresgruber** [comment]
Hi @alireza-dhp - thank you, finally we can reproduce this case. We suggest *not* delete the notifications in case of a study update. This will solve this case. The only downside would be, a participant might have an notification in his tab which is not more functional e.g. because a corresponding target observation has been removed during pausing the study.

**Comment by alireza-dhp** [comment]
Regarding our discussion at 4th sprint closing meeting, it would be acceptable to keep notifications when a study is updated, as previous notifications with unrelated observations would no longer serve their function due to being unobservable for participants.
