### ISSUE TITLE
Polar-Verity data-recording does not start automatically

### ISSUE THREAD

**Issue by ja-fra** [MORE-Platform/more-app-multiplatform#260]
Data capturing does not start **automatically** when the app is running in the foreground/background and the Polar device is connected. Instead, automatic data capturing only begins immediately after a successful connection to the Polar device.

So, if there is an upcoming polar observation and the participant connects the Polar device, data capturing does not start automatically, and the participant must initiate it manually.

If this is intended behaviour, why is it necessary to connect the Polar device immediately after signing up the participant?

(Affects both, **iOS** and **Android**)

----
Originally raised by @alireza-dhp in https://github.com/MORE-Platform/more-app-multiplatform/issues/200#issuecomment-2167941076

**Comment by alireza-dhp** [comment]
Dear @andresgruber, @janoliver20 

I have tested the automatic start of a Polar observation on both platforms using the latest version 4.0.12.

On iPhone 13 mini iOS version 17.5.1: Despite waiting a few minutes past the scheduled observation start time, the observation did not start automatically, even when the app was running in the foreground. No Polar connection error was reported.

On Google Pixle 3a XL Android version 12: After connecting to the Polar device, I received the error message "Heart rate measurement features unavailable...". Consequently, the Polar observation did not start, and the start button remained gray and disabled.

**Comment by andresgruber** [comment]
@alireza-dhp w.r.t the main issue: from your comment (“Polar observation did not start, and the start button remained gray and disabled”) I assume, that you did the test with VISIBLE polar observations.
- Please note, that visible observations won’t start automatically.
- Automatic start is implemented for *hidden* observations only.

**Comment by andresgruber** [comment]
- With version 4.0.14 the bug w.r.t. „heart rate measurement .. „ have been fixed. Note, that the message may still appear because may take some time before the feature is available.

- Automatic start of *hidden observations* are dependent on the status of More App on the mobile, which is controlled by the operating system. In principle:
    - If the app is in foreground, the observation will start automatically
    - If the app is in background, the start depends on whether the operating system allows to collect data. The rules to not allow this at all are more strict on Android systems than on iOS devices.
