### ISSUE TITLE
Improve Detail-Screen for Polar Verity Observations

### ISSUE THREAD

**Issue by ja-fra** [MORE-Platform/more-app-multiplatform#262]
It would be better to anchor the capture data button and error message label to the bottom of the page.

![image](https://github.com/MORE-Platform/more-app-multiplatform/assets/1815139/4b088382-a56f-4b07-80ff-476f804fe0cf)

----
Originally raised by @alireza-dhp in https://github.com/MORE-Platform/more-app-multiplatform/issues/200#issuecomment-2167941076

**Comment by andresgruber** [comment]
The „device“ button is now shown at the bottom for both versions of the App (Android and iOS)
