### ISSUE TITLE
Hidden Error-Message on Polar Observation Screen

### ISSUE THREAD

**Issue by ja-fra** [MORE-Platform/more-app-multiplatform#263]
The error message is unreadable on the Polar observation page.

![image](https://github.com/MORE-Platform/more-app-multiplatform/assets/1815139/fbd3a001-d811-49be-a86e-5a23276fdcba)

----
Originally raised by @alireza-dhp in https://github.com/MORE-Platform/more-app-multiplatform/issues/200#issuecomment-2167941076

**Comment by andresgruber** [comment]
The error message is now readable for both versions of the App (Android and iOS)
