### ISSUE TITLE
Messages change to read status on tapping in Android platform

### ISSUE THREAD

**Issue by alireza-dhp** [MORE-Platform/more-app-multiplatform#269]
Dear @janoliver20, @andresgruber, 

Regarding our meeting today:

Please ensure that when a user taps on a message in the notification tab on the Android platform, the message status changes to "read." Currently, users must tap exactly on the red dot button to mark a message as read.

**Comment by janoliver20** [comment]
https://github.com/MORE-Platform/more-app-multiplatform/pull/282

**Comment by andresgruber** [comment]
Tested with Android14 and iOS18.
